health-elasticsearch:
  container_name: health-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/health/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
health-postgresql:
  container_name: health-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/health/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=health
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
