health-dev-postgresql:
  container_name: health-dev-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/health/dev-postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=health
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
